GET http://localhost:5000/

###
POST http://localhost:5000/api/signup
Content-Type: application/json

{"username": "yeshi", "email": "yeshialemu64@gmail.com", "password": "amuamuamu"}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{"username": "alem", "password": "alemalem"}

###
POST http://localhost:5000/api/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NGVjZmJjOGI3OTI4YWI1MDBhZGEwMyIsImlhdCI6MTc1MDE1NTk5MSwiZXhwIjoxNzUwMjQyMzkxfQ.efmNTGHrdEM1FsrwfgzkqsQ56Ql1dOwYlWpCuVnyiIg; Max-Age=604800; Path=/; Expires=Tue, 24 Jun 2025 10:26:31 GMT; HttpOnly; SameSite=Lax

###
POST http://localhost:5000/api/afterLogout
Content-Type: application/json


{"name": "wonde"}

###
POST http://localhost:5000/api/me
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NTE0NmE4MzQ1MmM1MThiYzM2YmRmZSIsImlhdCI6MTc1MDM1OTcwOCwiZXhwIjoxNzUwNDQ2MTA4fQ.WX1ifs054oFBbip0Q30V9fxAyfgRFml50VJzapQgihI; Max-Age=604800; Path=/; Expires=Thu, 26 Jun 2025 19:01:48 GMT; HttpOnly; SameSite=Lax

###
POST http://localhost:5000/api/forgot-password
Content-Type: application/json


{"resEmail": "wondiradabebe@gmail.com"}
