GET http://localhost:5000/

###
POST http://localhost:5000/api/signup
Content-Type: application/json

{"username": "userWithRole", "email": "won.babg@gmail.com", "password": "password"}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{"username": "userWithRole-Admin", "password": "password"}

###
POST http://localhost:5000/api/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJXaXRoUm9sZS1BZG1pbiIsImlkIjoiNjg1YTcyYTRhNWQ5ZjU0NWY2OGE1YTcxIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzUwNzU4MzM0LCJleHAiOjE3NTA4NDQ3MzR9.zidmRWq4p4DsFt6hQvwPM1-VnK3U2MoB145f8AHESN0; Max-Age=604800; Path=/; Expires=Tue, 01 Jul 2025 09:45:34 GMT; HttpOnly; Secure; SameSite=None


###
POST http://localhost:5000/api/me
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NTE0NmE4MzQ1MmM1MThiYzM2YmRmZSIsImlhdCI6MTc1MDM1OTcwOCwiZXhwIjoxNzUwNDQ2MTA4fQ.WX1ifs054oFBbip0Q30V9fxAyfgRFml50VJzapQgihI; Max-Age=604800; Path=/; Expires=Thu, 26 Jun 2025 19:01:48 GMT; HttpOnly; SameSite=Lax

###
POST http://localhost:5000/api/forgot-password
Content-Type: application/json


{"resEmail": "wondiradabebe@gmail.com"}
